---
title: "RSQLServer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# On AWS, set timezone for the R enviroment
#Sys.setenv(TZ="GMT")
```

## Importing SQL Server data into R

Load the RODBC package:
```{r RODBC}
library(RODBC)
options(warn = -1)
```

Define the connection:
```{r connection}
#print(grepl("r", getwd(), ignore.case=TRUE))
if (!grepl("r", getwd(), ignore.case=TRUE)) {
  setwd(paste0(getwd(),"/sql-server-with-r"))
}
print(getwd())

cred_file <- file("./passwd")
creds <- readLines(cred_file)
#print(creds[1])
#print(creds[2])
close(cred_file)

# On Windows
#driver <- "Driver=SQL Server"
# On Linux / Mac OS X:
driver <- "Driver={ODBC Driver 17 for SQL Server}"

# Local
#server <- "Server=WIN-VHQQULMEB4K;trusted_connection=true"
# Remote
server <- paste0("Server=ec2-52-21-198-129.compute-1.amazonaws.com;Trusted_Connection=no;UID=", creds[1], ";PWD=", creds[2])

connStr <- paste0(driver, ";", server, ";Database=WideWorldImporters;{Persist Security Info=True};")
print(connStr)

dbHandle <- RODBC::odbcDriverConnect(connStr)
```

Define the query
```{r query}
order_query <- "select top 100 DATEFROMPARTS(YEAR(o.[OrderDate]), MONTH(o.[OrderDate]), 1) As OrderMonth,
  sp.[PreferredName] as SalesPerson,
  COUNT(distinct o.[OrderId]) as OrderCount,
  SUM(ol.[Quantity] * ol.[UnitPrice]) as TotalAmount
	from [Sales].[Orders] o
	  inner join [Sales].[OrderLines] ol
	    on ol.[OrderId] = o.[OrderId]
	  inner join [Application].[People] sp
	    on sp.[PersonId] = o.[SalespersonPersonId]
	where sp.[ValidTo] >= GETDATE()
	  and o.[OrderDate] between '20150101' and '20151231'
	group by DATEFROMPARTS(YEAR(o.[OrderDate]), MONTH(o.[OrderDate]), 1), sp.[PreferredName]
  order by OrderCount DESC;"
```

Execute the query and store the results
```{r results}
orders <- RODBC::sqlQuery(dbHandle, order_query)
View(orders)
str(orders)
```

First thing we need to do is convert the OrderMonth (: Factor) column to a real R date, then do some additional data munging, using native R functions:
```{r r_data_munging}
# Create new OrderMonth (: Date) column
order_dates <- data.frame(
  OrderMonth = as.Date(orders$OrderMonth)
)
# Bind OrderMonth (: Date) column to subset of orders, where original OrderMonth column has been removed
orders <- cbind(order_dates, orders[, !names(orders) == "OrderMonth"]) 
#orders <- cbind(order_dates, subset(orders, select = c(SalesPerson, OrderCount, TotalAmount)))

str(orders)

tail(orders)
new_orders <- data.frame(
  OrderMonth = c(as.Date("2019-12-01"), as.Date("2020-03-01")),
  SalesPerson = c(as.character("Julie"), as.character("Tomaz")),
  OrderCount = c(201, 2221),
  TotalAmount = c(340000, 370000)
)

tail(rbind(orders, new_orders)) # creates new data.frame

orders_discount <- data.frame(
    Discount = orders$TotalAmount * 0.25
)
orders_with_discount <- cbind(orders, orders_discount)

print(names(orders_with_discount))
```

The dplyr package makes many of these data munging tasks easier:
```{r dplyr_data_munging}
if (!require("dplyr")) {
  install.packages("dplyr")
  library("dplyr")
}

tail(dplyr::bind_rows(orders, new_orders))

orders_sequence <- data.frame(
    RowID = seq(1:nrow(orders))
)
orders_in_sequence <- dplyr::bind_cols(orders_sequence, orders_with_discount)

orders_tax <- data.frame(
    SalesTax = orders$TotalAmount * 0.08
)
orders_with_tax_and_discount <- dplyr::bind_cols(orders_in_sequence, data.frame(orders_tax))
tail(orders_with_tax_and_discount)

orders_checkout_total <- dplyr::mutate(
    orders_with_tax_and_discount, 
    CheckoutTotal = orders_with_tax_and_discount$TotalAmount - orders_with_tax_and_discount$Discount + orders_with_tax_and_discount$SalesTax
)
tail(orders_checkout_total)
```

```{r data_columns}
names(orders)
names(orders_with_discount)
names(orders_with_tax_and_discount)
names(orders_checkout_total)
```
```{r data_filter_grep}
order_sales_A <- grep("^A.*", orders$SalesPerson)
head(orders_checkout_total[order_sales_A,])
```

```{r dplyr_data_filter_grep}
head(dplyr::filter(orders_checkout_total, grepl("^A.*", SalesPerson)))
print(orders_checkout_total[order_sales_A,] == dplyr::filter(orders_checkout_total, grepl("^A.*", SalesPerson)))
```

```{r dplyr_data_selection}
head(dplyr::select(orders, matches("Order")))
head(dplyr::select(orders, c(-OrderCount, -TotalAmount)))
head(dplyr::select(orders_with_tax_and_discount, -RowID))
```
